"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
var awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cloud_logic_custom": [{
    "name": "iformapi",
    "endpoint": "https://h10xrszoge.execute-api.us-east-1.amazonaws.com/dev",
    "region": "us-east-1"
  }]
};
var _default = awsmobile;
exports["default"] = _default;
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _react = _interopRequireDefault(require("react"));

var _awsAmplify = require("aws-amplify");

var _awsExports = _interopRequireDefault(require("./src/aws-exports"));

require("./src/App.css");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function _typeof(obj) { if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } return _assertThisInitialized(self); }

function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } }); if (superClass) _setPrototypeOf(subClass, superClass); }

function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }

var withAuthenticator = function withAuthenticator(WrappedComponent, ifbConfig) {
  _awsAmplify.API.configure(_awsExports["default"]);

  var servername = ifbConfig.servername,
      client_id = ifbConfig.client_id,
      redirect_uri = ifbConfig.redirect_uri;

  var buildAuthorizeUrl = function buildAuthorizeUrl() {
    var authorizeUrl = 'https://' + servername + '.iformbuilder.com/exzact/api/oauth/auth?client_id=' + client_id + '&redirect_uri=' + redirect_uri + '&response_type=code';
    return authorizeUrl;
  };
  /* 
   * Logout does not work yet
   *
  const buildLogoutUrl = ()=> {
   const logoutUrl = 
    'https://'+servername+'.iformbuilder.com/exzact/logoutZWS.php?redirect='+redirect_uri
   return logoutUrl
   } 
   */


  var accessTokenGood = function accessTokenGood() {
    var access_token = window.localStorage.getItem('access_token');
    var exp = window.localStorage.getItem('access_token_expiration');
    return access_token && exp > Date.now();
  };

  var isLoggedIn = function isLoggedIn() {
    if (accessTokenGood()) return true;else {
      //Just logged in. Go get access_token
      var redirectUrl = window.location.href;
      var requestTokenMatch = redirectUrl.match(/code=([^&]+)/);

      if (requestTokenMatch) {
        var requestToken = requestTokenMatch[1];
        var myInit = {
          body: {
            code: requestToken,
            redirect_uri: redirect_uri
          }
        };

        _awsAmplify.API.post('iformapi', '/token', myInit).then(function (response) {
          if (response.token) {
            var access_token = response.token.access_token;
            var exp = Date.now() + response.token.expires_in * 1000;
            window.localStorage.setItem('access_token', access_token);
            window.localStorage.setItem('access_token_expiration', exp);
          }

          return true;
        })["catch"](function (error) {
          console.log(error);
          return false;
        });
      }
    }
  };

  if (!isLoggedIn()) return (
    /*#__PURE__*/
    function (_React$Component) {
      _inherits(_class, _React$Component);

      function _class() {
        _classCallCheck(this, _class);

        return _possibleConstructorReturn(this, _getPrototypeOf(_class).apply(this, arguments));
      }

      _createClass(_class, [{
        key: "componentDidMount",
        value: function componentDidMount() {
          window.location = buildAuthorizeUrl();
        }
      }, {
        key: "render",
        value: function render() {
          return _react["default"].createElement("div", {
            className: "App"
          }, _react["default"].createElement("header", {
            className: "App-header"
          }, "Redirecting..."));
        }
      }]);

      return _class;
    }(_react["default"].Component)
  );
  return (
    /*#__PURE__*/
    function (_React$Component2) {
      _inherits(_class2, _React$Component2);

      function _class2() {
        _classCallCheck(this, _class2);

        return _possibleConstructorReturn(this, _getPrototypeOf(_class2).apply(this, arguments));
      }

      _createClass(_class2, [{
        key: "render",
        value: function render() {
          return _react["default"].createElement("div", null, _react["default"].createElement(WrappedComponent, this.props));
        }
      }]);

      return _class2;
    }(_react["default"].Component)
  );
};

var _default = withAuthenticator;
exports["default"] = _default;
