// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

var iformConfig = {
    endpoint: "http://iformapi.zerionconsulting.com/iform",
    ACCESSTOKEN_KEY: "iform_token",
    ACCESSTOKEN_EXP_KEY: "iform_token_exp",
    SERVERNAME_KEY: "iform_servername",
    REDIRECT_KEY: "iform_redirect_uri"
};


export {iformConfig }
